In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("data/dataset.csv")
df.head()

/var/folders/cl/wqxhc67j255bdr0rmv_bl3580000gn/T/ipykernel_59543/2799292529.py:1: DtypeWarning: Columns (9,12,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/dataset.csv")


Unnamed: 0  SessionID                Start                  End     kWh  \
0           0     591686  2021-01-01 00:05:34  2021-01-01 00:31:22   6.033   
1           1     591720  2021-01-01 01:40:37  2021-01-01 01:42:19   0.890   
2           2     591749  2021-01-01 02:12:35  2021-01-01 03:07:36   3.300   
3           3     591755  2021-01-01 02:32:21  2021-01-01 02:57:08   6.880   
4           4     591783  2021-01-01 03:39:03  2021-01-01 04:02:05  12.630   

  Revenue   City  PortNum     PortType Adapter  ... Tariff  MaxPower Fishka  \
0   27.15   Київ        3  Type 2 Plug   False  ...   4.50       NaN   True   
1    6.22   Київ        1      CHAdeMO   False  ...   6.99       NaN   True   
2   14.85  Стрый        1       Type 2   False  ...   4.50       NaN   True   
3   48.09   Київ        1      CHAdeMO   False  ...   6.99       NaN   True   
4   56.84   Київ        3  Type 2 Plug   False  ...   4.50       NaN   True   

  Successful DisconnectionReason  Latitude  Longitude  Type_SLOW  \
0       True                 NaN  50.43104   30.39037          0   
1       True                 NaN  50.48207   30.48725          0   
2       True                 NaN  49.24778   23.85610          1   
3       True                 NaN  50.48207   30.48725          0   
4       True                 NaN  50.43104   30.39037          0   

   Type_ULTRAFAST  ChargingTime  
0               0         25.80  
1               0          1.70  
2               0         55.02  
3               0         24.78  
4               0         23.03  

[5 rows x 21 columns]

In [9]:
df['Successful'].unique()

array([True, nan], dtype=object)

In [17]:
df_cleaned = df.dropna(subset=['Successful'])
df_cleaned = df_cleaned.drop(columns = ['Successful', 'Unnamed: 0'])
df_cleaned

SessionID                Start                  End     kWh Revenue  \
0          591686  2021-01-01 00:05:34  2021-01-01 00:31:22   6.033   27.15   
1          591720  2021-01-01 01:40:37  2021-01-01 01:42:19   0.890    6.22   
2          591749  2021-01-01 02:12:35  2021-01-01 03:07:36   3.300   14.85   
3          591755  2021-01-01 02:32:21  2021-01-01 02:57:08   6.880   48.09   
4          591783  2021-01-01 03:39:03  2021-01-01 04:02:05  12.630   56.84   
...           ...                  ...                  ...     ...     ...   
372182    2486542  2024-10-31 23:27:29  2024-10-31 23:35:31   1.400   22.39   
372183    2486548  2024-10-31 23:39:18  2024-11-01 00:06:30  44.931  763.38   
372184    2486554  2024-10-31 23:50:28  2024-10-31 23:57:16  13.338  226.61   
372185    2486555  2024-10-31 23:50:34  2024-11-01 00:16:22  13.718  233.07   
372186    2486556  2024-10-31 23:50:43  2024-11-01 01:43:12  58.693  997.19   

                City  PortNum     PortType Adapter     Client  Tariff  \
0               Київ        3  Type 2 Plug   False  553804960    4.50   
1               Київ        1      CHAdeMO   False  550843379    6.99   
2              Стрый        1       Type 2   False  540085134    4.50   
3               Київ        1      CHAdeMO   False  828881697    6.99   
4               Київ        3  Type 2 Plug   False  553804960    4.50   
...              ...      ...          ...     ...        ...     ...   
372182          Київ        2      CHAdeMO     NaN  823585024   15.99   
372183  Біла Криниця        1        CCS 2     NaN  544295795   16.99   
372184   Нерубайське        1        CCS 2     NaN  603258103   16.99   
372185       Солонка        1        CCS 2     NaN  535769215   16.99   
372186   Нерубайське        1        CCS 2     NaN  858162982   16.99   

       MaxPower Fishka  DisconnectionReason  Latitude  Longitude  Type_SLOW  \
0           NaN   True                  NaN  50.43104   30.39037          0   
1           NaN   True                  NaN  50.48207   30.48725          0   
2           NaN   True                  NaN  49.24778   23.85610          1   
3           NaN   True                  NaN  50.48207   30.48725          0   
4           NaN   True                  NaN  50.43104   30.39037          0   
...         ...    ...                  ...       ...        ...        ...   
372182     16.0    NaN  Дистанційна зупинка  50.46754   30.35680          0   
372183    119.0    NaN                  NaN  50.60912   26.37798          0   
372184    148.0    NaN   Недостатньо коштів  46.53692   30.65360          0   
372185     38.0    NaN   Недостатньо коштів  49.75055   24.01561          0   
372186     91.0   True   Недостатньо коштів  46.53692   30.65360          0   

        Type_ULTRAFAST  ChargingTime  
0                    0         25.80  
1                    0          1.70  
2                    0         55.02  
3                    0         24.78  
4                    0         23.03  
...                ...           ...  
372182               0          8.03  
372183               1         27.20  
372184               1          6.80  
372185               1         25.80  
372186               1        112.48  

[178320 rows x 19 columns]

In [ ]:
df_cleaned.to_csv('unsuccessful.csv')

In [30]:
def summarize_dataframe(df):
    summary = {}
    
    for col in df.columns:
        # Initialize column summary
        col_summary = {}
        
        # Mean
        col_summary['mean'] = df[col].mean() if pd.api.types.is_numeric_dtype(df[col]) else None
        
        # Data type
        col_summary['dtype'] = df[col].dtype
        
        # Percentiles
        if pd.api.types.is_numeric_dtype(df[col]):
            percentiles = df[col].quantile([0.25, 0.5, 0.75]).to_dict()
            col_summary['25th_percentile'] = percentiles.get(0.25, None)
            col_summary['50th_percentile'] = percentiles.get(0.5, None)
            col_summary['75th_percentile'] = percentiles.get(0.75, None)
        else:
            col_summary['25th_percentile'] = None
            col_summary['50th_percentile'] = None
            col_summary['75th_percentile'] = None
        
        # NaN count
        col_summary['num_nans'] = df[col].isna().sum()
        
        # Add to summary
        summary[col] = col_summary
    
    # Convert summary to DataFrame
    summary_df = pd.DataFrame(summary).T
    return summary_df
df = pd.read_csv('data/clean/dataset.csv', index_col='idx')
summary = summarize_dataframe(df)
summary

/var/folders/5w/bchvy66s6vbgncfkws1skvf40000gp/T/ipykernel_30808/155250225.py:34: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/clean/dataset.csv', index_col='idx')


TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

In [31]:
df['Adapter'].unique()

array([False,  True])

In [32]:
df['PortType'].unique()

array(['Type 2 Plug', 'CHAdeMO', 'Type 2', 'Type 1', 'Type 2/Type 1',
       'CCS 2', 'CCS 2/CCS 1', 'CCS 2/GBT DC', 'GB/T DC', 'GB/T AC'],
      dtype=object)

In [33]:
df['PortNum'].unique()

array([3, 1, 2, 4])

In [35]:
df = pd.read_csv('data/clean/dataset.csv', index_col='idx')
df.dtypes

/var/folders/5w/bchvy66s6vbgncfkws1skvf40000gp/T/ipykernel_30808/3133157155.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/clean/dataset.csv', index_col='idx')


Start            object
End              object
kWh             float64
Revenue         float64
Station           int64
PortNum           int64
PortType         object
Adapter            bool
Client           object
Tariff          float64
MaxPower         object
Fishka           object
Latitude        float64
Longitude       float64
Type             object
ChargingTime    float64
dtype: object